segmentation:
  title: "FEW"
  class: 'unified_ar.segmentation.FixedEventWindow.FixedEventWindow'
  params:
    shift: 1
    size: 25
  range:
    shift:
      min: 2
      max: 20
      list: 10,15
    size:
      min: 10
      max: 30    
      list: 10,15,20,25